name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: task test

      - name: Build binary
        run: task build
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
          OUTPUT_FILE_SUFFIX: ${{ github.ref_name }}

      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.arch }}
          path: dist/*
